version: "3.8"
services:
  mysql:
    container_name: auth-with-clean-architecture-mysql
    image: mysql
    command: |
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --sql_mode=IGNORE_SPACE,NO_ENGINE_SUBSTITUTION
      --lower_case_table_names=2
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=username
      - MYSQL_PASSWORD=pasword
      - MYSQL_DATABASE=auth_with_clean_architecture
    healthcheck:
      test: "mysql auth_with_clean_architecture -uawesomeusername -pawesomepassword -e 'SELECT 1;'"
      interval: 5s
      timeout: 5s
      start_period: 30s
      retries: 60
    volumes:
      - volume:/var/lib/mysql
      - ../docs:/docker-entrypoint-initdb.d
    networks:
      - network
  go:
    container_name: auth-with-clean-architecture-go
    image: azisalvriyanto/auth-with-clean-architecture:stable
    restart: always
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    ports:
      - 1337:8080
    environment:
      - DB_USERNAME=username
      - DB_PASSWORD=password
      - DB_HOST=auth-with-clean-architecture-mysql
      - DB_PORT=3306
      - DB_DATABASE=auth_with_clean_architecture
      - JWT_KEY=secret-key
    networks:
      - network
    depends_on:
      - mysql
volumes:
  volume:
    name: auth-with-clean-architecture
    driver: local
networks:
  network:
    name: auth-with-clean-architecture
    driver: bridge
